# Generated by Django 4.1 on 2024-09-11 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Books',
        ),
    ]
