# Generated by Django 5.1.1 on 2024-09-22 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_remove_post_created_at_remove_post_slug_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
